const searchList = 
  {
    A: {"ticker": "A", "name": "Agilent"},
    AAL: {"ticker": "AAL", "name": "American Airlines"},
    AAPL: {"ticker": "AAPL", "name": "Apple"},
    ABB: {"ticker": "ABB", "name": "Abb Ltd"},
    ABC: {"ticker": "ABC", "name": "AmerisourceBergn"},
    ABEV: {"ticker": "ABEV", "name": "Ambev"},
    ABNB: {"ticker": "ABNB", "name": "Airbnb"},
    ABT: {"ticker": "ABT", "name": "Abbot Laboratories"},
    ABV: {"ticker": "ABV", "name": "AbbVie"},
    ACB: {"ticker": "ACB", "name": "Aurora Cannabis"},
    ACGL: {"ticker": "ACGL", "name": "Arch Capital Group"},
    ACN: {"ticker": "ACN", "name": "Accenture plc Class A"},
    ACST: {"ticker": "ACST", "name": "Acasti Pharma"},
    ADBE: {"ticker": "ADBE", "name": "Adobe"},
    ADI: {"ticker": "ADI", "name": "Analog Devices"},
    ADM: {"ticker": "ADM", "name": "Archer-Daniels-Midland"},
    ADP: {"ticker": "ADP", "name": "Automatic Data Processing"},
    ADSK: {"ticker": "ADSK", "name": "Autodesk"},
    AEE: {"ticker": "AEE", "name": "Ameren"},
    AEM: {"ticker": "AEM", "name": "Agnico Eagle Mines"},
    AEP: {"ticker": "AEP", "name": "American Electric Power"},
    AES: {"ticker": "AES", "name": "AES"},
    AFRM: {"ticker": "AFRM", "name": "Affirm Holdings"},
    AGR: {"ticker": "AGR", "name": "Avangrid"},
    AIG: {"ticker": "AIG", "name": "American International Group"},
    AJG: {"ticker": "AJG", "name": "Arthur J Gallagher"},
    AKAM: {"ticker": "AKAM", "name": "Akamai Technologies"},
    ALB: {"ticker": "ALB", "name": "Albemarle"},
    ALC: {"ticker": "ALC", "name": "Alcon"},
    ALGN: {"ticker": "ALGN", "name": "Align"},
    ALL: {"ticker": "ALL", "name": "Allstate"},
    ALLY: {"ticker": "ALLY", "name": "Ally Financial"},
    ALNY: {"ticker": "ALNY", "name": "Alnylam Pharmaceuticals"},
    ALXN: {"ticker": "ALXN", "name": "Alexion"},
    AMAT: {"ticker": "AMAT", "name": "Applied Materials"},
    AMC: {"ticker": "AMC", "name": "AMC Entertainment"},
    AMCR: {"ticker": "AMCR", "name": "Amcor"},
    AMCX: {"ticker": "AMCX", "name": "AMC Networks"},
    AMD: {"ticker": "AMD", "name": "Advanced Micro Devices"},
    AME: {"ticker": "AME", "name": "AMTEK"},
    AMGN: {"ticker": "AMGN", "name": "Amgen"},
    AMJ: {"ticker": "AMJ", "name": "JPMorgan Ultra-Short Municipal Income ETF"},
    AMOV: {"ticker": "AMOV", "name": "American Movil"},
    AMP: {"ticker": "AMP", "name": "Ameriprise"},
    AMT: {"ticker": "AMT", "name": "American Tower"},
    AMTX: {"ticker": "AMTX", "name": "Aemetis Inc"},
    AMX: {"ticker": "AMX", "name": "America Movil"},
    AMZN: {"ticker": "AMZN", "name": "Amazon"},
    ANET: {"ticker": "ANET", "name": "Arista"},
    ANSS: {"ticker": "ANSS", "name": "ANSYS"},
    ANTM: {"ticker": "ANTM", "name": "Anthem"},
    AON: {"ticker": "AON", "name": "Aon"},
    APD: {"ticker": "APD", "name": "Air Products and Chemicals"},
    APH: {"ticker": "APH", "name": "Amphenol"},
    APP: {"ticker": "APP", "name": "Applovin"},
    APTV: {"ticker": "APTV", "name": "Aptiv"},
    ARE: {"ticker": "ARE", "name": "Alecandria Real Estate Equities"},
    ARKK: {"ticker": "ARKK", "name": "ARK Innovation ETF"},
    ARPO: {"ticker": "ARPO", "name": "Aerpio Pharmaceuticals"},
    ASML: {"ticker": "ASML", "name": "ASML Holding"},
    ASXC: {"ticker": "ASXC", "name": "Asensus Surgical"},
    ATUS: {"ticker": "ATUS", "name": "Atlice USA"},
    ATVI: {"ticker": "ATVI", "name": "Activision Blizzard"},
    AVB: {"ticker": "AVB", "name": "AvalonBay"},
    AVGO: {"ticker": "AVGO", "name": "Broadcom"},
    AVTR: {"ticker": "AVTR", "name": "Avantor"},
    AVY: {"ticker": "AVY", "name": "Avery Dennison"},
    AWK: {"ticker": "AWK", "name": "American Water Works"},
    AXP: {"ticker": "AXP", "name": "American Express"},
    AZN: {"ticker": "AZN", "name": "AstraZeneca"},
    AZO: {"ticker": "AZO", "name": "AutoZone"},
    BA: {"ticker": "BA", "name": "Boeing"},
    BABA: {"ticker": "BABA", "name": "Alibaba"},
    BAC: {"ticker": "BAC", "name": "Bank of America"},
    BAM: {"ticker": "BAM", "name": "Brookfield Asset Management"},
    BAX: {"ticker": "BAX", "name": "Baxter"},
    BB: {"ticker": "BB", "name": "Blackberry"},
    BBBY: {"ticker": "BBBY", "name": "Bed Bath & Beyond"},
    BBD: {"ticker": "BBD", "name": "Banco Bradesco"},
    BBDO: {"ticker": "BBDO", "name": "Banco Bradesco"},
    BBL: {"ticker": "BBL", "name": "BHP Group"},
    BBVA: {"ticker": "BBVA", "name": "Banco Bilbao"},
    BBY: {"ticker": "BBY", "name": "Best Buy"},
    BCE: {"ticker": "BCE", "name": "BCE"},
    BCS: {"ticker": "BCS", "name": "Barclays"},
    BDX: {"ticker": "BDX", "name": "Becton, Dickinson & Company"},
    BEKE: {"ticker": "BEKE", "name": "KE Holdings"},
    BEN: {"ticker": "BEN", "name": "Franklin Resources"},
    BGFV: {"ticker": "BGFV", "name": "Big 5"},
    BGNE: {"ticker": "BGNE", "name": "BeiGene"},
    BHP: {"ticker": "BHP", "name": "BHP Group"},
    BIDU: {"ticker": "BIDU", "name": "Baidu"},
    BIIB: {"ticker": "BIIB", "name": "Biogen"},
    BILI: {"ticker": "BILI", "name": "Bilibili"},
    BIO: {"ticker": "BIO", "name": "Bio-Rad Laboratories"},
    BIP: {"ticker": "BIP", "name": "Brookfield Infastructure Partners"},
    BK: {"ticker": "BK", "name": "The Bank of New York Mellon"},
    BKNG: {"ticker": "BKNG", "name": "Booking Holdings"},
    BKR: {"ticker": "BKR", "name": "Baker Hughes"},
    BLK: {"ticker": "BLK", "name": "BlackRock"},
    BLL: {"ticker": "BLL", "name": "Ball"},
    BLNK: {"ticker": "BLNK", "name": "Blink Charging"},
    BLUE: {"ticker": "BLUE", "name": "Bluebird bio"},
    BMBL: {"ticker": "BMBL", "name": "Bumble"},
    BMO: {"ticker": "BMO", "name": "Bank of Montreal"},
    BMRN: {"ticker": "BMRN", "name": "BioMarin"},
    BMWYY: {"ticker": "BMWYY", "name": "BMW"},
    BMY: {"ticker": "BMY", "name": "Bristol-Myers Squibb"},
    BNGO: {"ticker": "BNGO", "name": "Bionano Genomics"},
    BNS: {"ticker": "BNS", "name": "Bank of Nova Scotia"},
    BNTX: {"ticker": "BNTX", "name": "BioNTech"},
    BP: {"ticker": "BP", "name": "BP plc"},
    BPY: {"ticker": "BPY", "name": "Brookfield Property Partners"},
    BR: {"ticker": "BR", "name": "Broadridge Financial Solutions"},
    BRKA: {"ticker": "BRK.A", "name": "Berkshire Hathaway"},
    BRKB: {"ticker": "BRK.B", "name": "Berkshire Hathaway"},
    BSBR: {"ticker": "BSBR", "name": "Banco Santander Brasil"},
    BSX: {"ticker": "BSX", "name": "Boston Scientific"},
    BSY: {"ticker": "BSY", "name": "Bently Systems"},
    BTI: {"ticker": "BTI", "name": "British American Tobacco Industry"},
    BUD: {"ticker": "BUD", "name": "Anheuser-Busch Inbev"},
    BURL: {"ticker": "BURL", "name": "Burlington Stores"},
    BX: {"ticker": "BX", "name": "The Blackstone Group"},
    BXP: {"ticker": "BXP", "name": "Boston Properties"},
    BYDDY: {"ticker": "BYDDY", "name": "BYD Company"},
    BYND: {"ticker": "BYND", "name": "Beyond Meat"},
    C: {"ticker": "C", "name": "Citigroup"},
    CAG: {"ticker": "CAG", "name": "ConAgra Brands"},
    CAH: {"ticker": "CAH", "name": "Cardinal Health"},
    CAJ: {"ticker": "CAJ", "name": "Canon"},
    CARR: {"ticker": "CARR", "name": "Carrier Global"},
    CAT: {"ticker": "CAT", "name": "Caterpillar"},
    CB: {"ticker": "CB", "name": "Chubb Limited"},
    CBRE: {"ticker": "CBRE", "name": "CBRE"},
    CCEP: {"ticker": "CCEP", "name": "Coca-Cola Europacific Partners"},
    CCI: {"ticker": "CCI", "name": "Crown Castle International"},
    CCIV: {"ticker": "CCIV", "name": "Churchill Capital"},
    CCL: {"ticker": "CCL", "name": "Carnival"},
    CDNS: {"ticker": "CDNS", "name": "Cadence Design Systems"},
    CDW: {"ticker": "CDW", "name": "CDW Corp"},
    CE: {"ticker": "CE", "name": "Celanese"},
    CERN: {"ticker": "CERN", "name": "Cerner"},
    CFG: {"ticker": "CFG", "name": "Citizens Financial Group"},
    CG: {"ticker": "CG", "name": "Carlyle Group"},
    CGC: {"ticker": "CGC", "name": "Canopy Growth"},
    CHD: {"ticker": "CHD", "name": "Church & Dwight"},
    CHKP: {"ticker": "CHKP", "name": "Check Point Software"},
    CHPT: {"ticker": "CHPT", "name": "ChargePoint"},
    CHT: {"ticker": "CHT", "name": "Chunghwa Telecom"},
    CHTR: {"ticker": "CHTR", "name": "Charter Communications"},
    CHWY: {"ticker": "CHWY", "name": "Chewy"},
    CI: {"ticker": "CI", "name": "Cigna"},
    CINF: {"ticker": "CINF", "name": "Cincinatti Financial Corp"},
    CL: {"ticker": "CL", "name": "Colgate"},
    CLVT: {"ticker": "CLVT", "name": "Clarivate"},
    CLX: {"ticker": "CLX", "name": "Clorox"},
    CM: {"ticker": "CM", "name": "Canadian Imperial Bank of Commerce"},
    CMCSA: {"ticker": "CMCSA", "name": "Comcast"},
    CME: {"ticker": "CME", "name": "CME Group"},
    CMG: {"ticker": "CMG", "name": "Chipotle"},
    CMI: {"ticker": "CMI", "name": "Cummins"},
    CMS: {"ticker": "CMS", "name": "CMS Energy"},
    CNC: {"ticker": "CNC", "name": "Centene"},
    CNHI: {"ticker": "CNHI", "name": "CHN Industrial"},
    CNI: {"ticker": "CNI", "name": "Canadian National Railway"},
    CNP: {"ticker": "CNP", "name": "CenterPoint Energy"},
    CNQ: {"ticker": "CNQ", "name": "Canadian Natural Resources"},
    COF: {"ticker": "COF", "name": "Capital One Financial"},
    COIN: {"ticker": "COIN", "name": "Coinbase"},
    COO: {"ticker": "COO", "name": "Cooper Companies"},
    COP: {"ticker": "COP", "name": "ConocoPhillips"},
    COST: {"ticker": "COST", "name": "Costco Wholesale"},
    COUP: {"ticker": "COUP", "name": "Coupa Software Inc"},
    CP: {"ticker": "CP", "name": "Canadian Pacific Railway"},
    CPNG: {"ticker": "CPNG", "name": "Coupang"},
    CPRT: {"ticker": "CPRT", "name": "Copart"},
    CPRX: {"ticker": "CPRX", "name": "Catalyst Pharmaceuticals"},
    CQP: {"ticker": "CQP", "name": "Cheniere Energy Partners"},
    CRBP: {"ticker": "CRBP", "name": "Corbus Pharmaceuticals"},
    CRH: {"ticker": "CRH", "name": "CRH"},
    CRL: {"ticker": "CRL", "name": "Charlers River Laboratories"},
    CRM: {"ticker": "CRM", "name": "Salesforce"},
    CRON: {"ticker": "CRON", "name": "Cronos Group"},
    CRWD: {"ticker": "CRWD", "name": "CrowdStrike"},
    CS: {"ticker": "CS", "name": "Credit Suisse"},
    CSAN: {"ticker": "CSAN", "name": "Cosan"},
    CSCO: {"ticker": "CSCO", "name": "Cisco"},
    CSGP: {"ticker": "CSGP", "name": "CoStar Group"},
    CSX: {"ticker": "CSX", "name": "CSX Corporation"},
    CTAS: {"ticker": "CTAS", "name": "Cintas"},
    CTLT: {"ticker": "CTLT", "name": "Catalent"},
    CTSH: {"ticker": "CTSH", "name": "Cognizant"},
    CTVA: {"ticker": "CTVA", "name": "Corteva"},
    CUK: {"ticker": "CUK", "name": "Carnival"},
    CVAC: {"ticker": "CVAC", "name": "CureVac"},
    CVE: {"ticker": "CVE", "name": "Cenovus Energy"},
    CVNA: {"ticker": "CVNA", "name": "Carvano"},
    CVS: {"ticker": "CVS", "name": "CVS Health"},
    CVX: {"ticker": "CVX", "name": "Chevron"},
    CYRX: {"ticker": "CYRX", "name": "CryoPort"},
    CZR: {"ticker": "CZR", "name": "Caesars Entertainment"},
    D: {"ticker": "D", "name": "Doiminion Energy"},
    DAC: {"ticker": "DAC", "name": "Danaos Corp"},
    DAL: {"ticker": "DAL", "name": "Delta Air Lines"},
    DASH: {"ticker": "DASH", "name": "DoorDash"},
    DB: {"ticker": "DB", "name": "Deutsche Bank"},
    DD: {"ticker": "DD", "name": "DuPont de Nemours"},
    DDOG: {"ticker": "DDOG", "name": "Datadog"},
    DE: {"ticker": "DE", "name": "Deere & Company"},
    DELL: {"ticker": "DELL", "name": "Dell"},
    DEO: {"ticker": "DEO", "name": "Diaegeo"},
    DFS: {"ticker": "DFS", "name": "Discover"},
    DG: {"ticker": "DG", "name": "Dollar General"},
    DGX: {"ticker": "DGX", "name": "Quest Diagnostics"},
    DHI: {"ticker": "DHI", "name": "D.R. Horton"},
    DHR: {"ticker": "DHR", "name": "Danaher"},
    DIS: {"ticker": "DIS", "name": "Disney"},
    DISCA: {"ticker": "DISCA", "name": "Discovery"},
    DISCB: {"ticker": "DISCB", "name": "Discovery"},
    DISCK: {"ticker": "DISCK", "name": "Discovery"},
    DISH: {"ticker": "DISH", "name": "DISH Network"},
    DIT: {"ticker": "DIT", "name": "Amcon Distributing"},
    DKNG: {"ticker": "DKNG", "name": "DraftKings"},
    DLR: {"ticker": "DLR", "name": "Digital Realty Trust"},
    DLTR: {"ticker": "DLTR", "name": "Dollar Tree"},
    DOCU: {"ticker": "DOCU", "name": "DocuSign"},
    DOV: {"ticker": "DOV", "name": "Dover"},
    DOW: {"ticker": "DOW", "name": "Dow"},
    DPZ: {"ticker": "DPZ", "name": "Domino's Pizza"},
    DRE: {"ticker": "DRE", "name": "Duke Realty"},
    DRI: {"ticker": "DRI", "name": "Darden Restaurants"},
    DT: {"ticker": "DT", "name": "Dynatrace"},
    DVN: {"ticker": "DVN", "name": "Devon Energy"},
    DXCM: {"ticker": "DXCM", "name": "DexCom"},
    E: {"ticker": "E", "name": "Eni"},
    EA: {"ticker": "EA", "name": "Electronic Artis"},
    EC: {"ticker": "EC", "name": "Ecopetrol"},
    ECL: {"ticker": "ECL", "name": "Ecolab"},
    ED: {"ticker": "ED", "name": "Consolidated Edison"},
    EDU: {"ticker": "EDU", "name": "New Oriential Education & Technology"},
    EFX: {"ticker": "EFX", "name": "Equifax"},
    EHTH: {"ticker": "EHTH", "name": "eHealth"},
    EIX: {"ticker": "EIX", "name": "Edison International"},
    EL: {"ticker": "EL", "name": "Estee Lauder"},
    ELAN: {"ticker": "ELAN", "name": "Elanco Animal Health"},
    ELP: {"ticker": "ELP", "name": "Paranaense de Energia"},
    EMB: {"ticker": "EMB", "name": "iShares JP Morgan USD Emerging Markets Bond ETF"},
    EMN: {"ticker": "EMN", "name": "Eastman Chemical"},
    EMR: {"ticker": "EMR", "name": "Emerson Electric"},
    ENPH: {"ticker": "ENPH", "name": "Enphase Energy"},
    ENTG: {"ticker": "ENTG", "name": "Entegris"},
    EOG: {"ticker": "EOG", "name": "EOG Resources"},
    EPAM: {"ticker": "EPAM", "name": "EPAM"},
    EPD: {"ticker": "EPD", "name": "Enterprise Products"},
    EPIX: {"ticker": "EPIX", "name": "Essa Pharma"},
    EQIX: {"ticker": "EQIX", "name": "Equinix"},
    EQNR: {"ticker": "EQNR", "name": "Equinor"},
    EQR: {"ticker": "EQR", "name": "Equity Residential"},
    ERIC: {"ticker": "ERIC", "name": "Ericsson"},
    ES: {"ticker": "ES", "name": "Eversource Energy"},
    ESS: {"ticker": "ESS", "name": "Essex Property Trust"},
    ET: {"ticker": "ET", "name": "Energy Transfer"},
    ETN: {"ticker": "ETN", "name": "Eaton"},
    ETR: {"ticker": "ETR", "name": "Entergy"},
    ETSY: {"ticker": "ETSY", "name": "Etsy"},
    EW: {"ticker": "EW", "name": "Edwards Lifesciences"},
    EXAS: {"ticker": "EXAS", "name": "Exact Sciences"},
    EXC: {"ticker": "EXC", "name": "Exelon"},
    EXPD: {"ticker": "EXPD", "name": "Expeditors International of Washington"},
    EXPE: {"ticker": "EXPE", "name": "Expedia"},
    EXPR: {"ticker": "EXPR", "name": "Express"},
    EXR: {"ticker": "EXR", "name": "Extra Space Storage"},
    F: {"ticker": "F", "name": "Ford Motor"},
    FAST: {"ticker": "FAST", "name": "Fastenal"},
    FB: {"ticker": "FB", "name": "Facebook"},
    FCEL: {"ticker": "FCEL", "name": "FuelCell Energy"},
    FCX: {"ticker": "FCX", "name": "Freeport-McMoRan"},
    FDX: {"ticker": "FDX", "name": "FedEx"},
    FE: {"ticker": "FE", "name": "FirstEnergy"},
    FERG: {"ticker": "FERG", "name": "Ferguson"},
    FIS: {"ticker": "FIS", "name": "Fidelity"},
    FISV: {"ticker": "FISV", "name": "Fiserv"},
    FITB: {"ticker": "FITB", "name": "Fifth Third Bancorp"},
    FLDM: {"ticker": "FLDM", "name": "Fluidigm"},
    FLT: {"ticker": "FLT", "name": "FleetCor"},
    FMC: {"ticker": "FMC", "name": "FMC Corp"},
    FMS: {"ticker": "FMS", "name": "Fresenius Medical Care"},
    FMX: {"ticker": "FMX", "name": "Fomento Economico Mexicano"},
    FNV: {"ticker": "FNV", "name": "Franco-Nevada"},
    FOX: {"ticker": "FOX", "name": "Fox Class B"},
    FOXA: {"ticker": "FOXA", "name": "Fox Class A"},
    FRC: {"ticker": "FRC", "name": "FIRST REPUBLIC BANK"},
    FSR: {"ticker": "FSR", "name": "Fisker"},
    FTCH: {"ticker": "FTCH", "name": "Farfetch Limited"},
    FTNT: {"ticker": "FTNT", "name": "Fortinet"},
    FTS: {"ticker": "FTS", "name": "Fortis"},
    FTV: {"ticker": "FTV", "name": "Fortive"},
    FUBO: {"ticker": "FUBO", "name": "Fubo"},
    FUTU: {"ticker": "FUTU", "name": "Futu Holdings"},
    FVRR: {"ticker": "FVRR", "name": "Fiverr"},
    GD: {"ticker": "GD", "name": "General Dynamics"},
    GDRX: {"ticker": "GDRX", "name": "GoodRx"},
    GE: {"ticker": "GE", "name": "General Electric"},
    GH: {"ticker": "GH", "name": "Guardant Health"},
    GIB: {"ticker": "GIB", "name": "CGI"},
    GILD: {"ticker": "GILD", "name": "Gilead Sciences"},
    GIS: {"ticker": "GIS", "name": "General Mills"},
    GLW: {"ticker": "GLW", "name": "Corning"},
    GM: {"ticker": "GM", "name": "General Motors"},
    GMAB: {"ticker": "GMAB", "name": "Genmab"},
    GME: {"ticker": "GME", "name": "GameStop"},
    GNRC: {"ticker": "GNRC", "name": "Generac Holdings"},
    GNUS: {"ticker": "GNUS", "name": "Genius Brands"},
    GOLD: {"ticker": "GOLD", "name": "Barrick Gold"},
    GOOG: {"ticker": "GOOG", "name": "Alphabet Class C"},
    GOOGL: {"ticker": "GOOGL", "name": "Alphabet Class A"},
    GOOS: {"ticker": "GOOS", "name": "Canada Goose"},
    GPC: {"ticker": "GPC", "name": "Genuine Parts"},
    GPN: {"ticker": "GPN", "name": "Globaal Payments"},
    GPRO: {"ticker": "GPRO", "name": "GoPro"},
    GRMN: {"ticker": "GRMN", "name": "Garmin"},
    GS: {"ticker": "GS", "name": "Goldman Sachs"},
    GSAT: {"ticker": "GSAT", "name": "Globalstar"},
    GSK: {"ticker": "GSK", "name": "GlaxoSmithKline"},
    GTIM: {"ticker": "GTIM", "name": "Good Times Rest"},
    GWW: {"ticker": "GWW", "name": "W.W. Grainger"},
    HAL: {"ticker": "HAL", "name": "Haliburton"},
    HBAN: {"ticker": "HBAN", "name": "Huntington Bancshares"},
    HCA: {"ticker": "HCA", "name": "HCA HealthCare"},
    HD: {"ticker": "HD", "name": "Home Depot"},
    HDB: {"ticker": "HDB", "name": "HDFC Bank"},
    HEI: {"ticker": "HEI", "name": "Heico"},
    HES: {"ticker": "HES", "name": "HESS"},
    HEXO: {"ticker": "HEXO", "name": "HEXO"},
    HIG: {"ticker": "HIG", "name": "Hartford Financial Services Group"},
    HLT: {"ticker": "HLT", "name": "Hilton Worldwide Holdings"},
    HMC: {"ticker": "HMC", "name": "Honda"},
    HOLX: {"ticker": "HOLX", "name": "Hologic"},
    HON: {"ticker": "HON", "name": "Honeywell"},
    HPE: {"ticker": "HPE", "name": "Hewlett Packard"},
    HPQ: {"ticker": "HPQ", "name": "HP"},
    HRL: {"ticker": "HRL", "name": "Hormel Foods"},
    HSBC: {"ticker": "HSBC", "name": "HSBC Holdings"},
    HSY: {"ticker": "HSY", "name": "Hershey"},
    HTHT: {"ticker": "HTHT", "name": "Huazhu Group"},
    HUBS: {"ticker": "HUBS", "name": "HubSpot"},
    HUM: {"ticker": "HUM", "name": "Humana"},
    HWM: {"ticker": "HWM", "name": "Howmet Aerospace"},
    HZNP: {"ticker": "HZNP", "name": "Horizon Therapeutics"},
    IAC: {"ticker": "IAC", "name": "IAC"},
    IBIO: {"ticker": "IBIO", "name": "iBio"},
    IBKR: {"ticker": "IBKR", "name": "Interactive Brokers Group"},
    IBM: {"ticker": "IBM", "name": "International Business Machines"},
    IBN: {"ticker": "IBN", "name": "ICICI Bank"},
    ICE: {"ticker": "ICE", "name": "Intercontinental Exchange"},
    IDEX: {"ticker": "IDEX", "name": "Ideanomics"},
    IDXX: {"ticker": "IDXX", "name": "IDEXX Laboratories"},
    IEX: {"ticker": "IEX", "name": "IDEX"},
    IFF: {"ticker": "IFF", "name": "International Flavors & Fragrances"},
    ILMN: {"ticker": "ILMN", "name": "Illumina"},
    IMO: {"ticker": "IMO", "name": "Imperial Oil"},
    INCY: {"ticker": "INCY", "name": "Incyte"},
    INFO: {"ticker": "INFO", "name": "IHS Markit"},
    INFY: {"ticker": "INFY", "name": "Infosys"},
    ING: {"ticker": "ING", "name": "ING"},
    INO: {"ticker": "INO", "name": "Inovio"},
    INPX: {"ticker": "INPX", "name": "Inpixon"},
    INTC: {"ticker": "INTC", "name": "Intel"},
    INTU: {"ticker": "INTU", "name": "Intuit"},
    INVH: {"ticker": "INVH", "name": "Invitation Homes"},
    IP: {"ticker": "IP", "name": "international Paper Company"},
    IQV: {"ticker": "IQV", "name": "IQVIA Holdings"},
    IR: {"ticker": "IR", "name": "Ingersoll Rand"},
    IRBT: {"ticker": "IRBT", "name": "iRobot"},
    ISRG: {"ticker": "ISRG", "name": "Intuitive Surgical"},
    IT: {"ticker": "IT", "name": "Gartner"},
    ITUB: {"ticker": "ITUB", "name": "Itau Unibanco"},
    ITW: {"ticker": "ITW", "name": "Illinois Tools Works"},
    IVR: {"ticker": "IVR", "name": "Invesco Mortgage Capital"},
    IX: {"ticker": "IX", "name": "Orix"},
    J: {"ticker": "J", "name": "Jacobs Engineering Group"},
    JBHT: {"ticker": "JBHT", "name": "J.B. Hunt Transport Services"},
    JBLU: {"ticker": "JBLU", "name": "JetBlue Airways"},
    JCI: {"ticker": "JCI", "name": "Johnson Controls International"},
    JD: {"ticker": "JD", "name": "JD.com"},
    JNJ: {"ticker": "JNJ", "name": "Johnson & Johnson"},
    JPM: {"ticker": "JPM", "name": "JPMorgan Chase"},
    JPST: {"ticker": "JPST", "name": "JPMorgan Ultra-Short Income ETF"},
    K: {"ticker": "K", "name": "Kellogg"},
    KB: {"ticker": "KB", "name": "KB Financial"},
    KDP: {"ticker": "KDP", "name": "Keurig Dr Pepper"},
    KEP: {"ticker": "KEP", "name": "Korea Electric power"},
    KEY: {"ticker": "KEY", "name": "KeyCorp"},
    KEYS: {"ticker": "KEYS", "name": "Keysight Technologies"},
    KHC: {"ticker": "KHC", "name": "Kraft Foods"},
    KIRK: {"ticker": "KIRK", "name": "Kirkland's"},
    KKR: {"ticker": "KKR", "name": "KKR"},
    KLAC: {"ticker": "KLAC", "name": "KLA"},
    KMB: {"ticker": "KMB", "name": "Kimberly-Clark"},
    KMI: {"ticker": "KMI", "name": "Kinder Morgan"},
    KMX: {"ticker": "KMX", "name": "CarMax"},
    KO: {"ticker": "KO", "name": "Coca-Cola"},
    KR: {"ticker": "KR", "name": "Kroger"},
    KSU: {"ticker": "KSU", "name": "Kansas City Southern"},
    L: {"ticker": "L", "name": "Loews"},
    LB: {"ticker": "LB", "name": "L Brands"},
    LBRDA: {"ticker": "LBRDA", "name": "Liberty Broadband"},
    LBRDK: {"ticker": "LBRDK", "name": "Liberty Broadband"},
    LBTYA: {"ticker": "LBTYA", "name": "Liberty Global"},
    LBTYK: {"ticker": "LBTYK", "name": "Liberty Global"},
    LCRX: {"ticker": "LCRX", "name": "Lam Research"},
    LEN: {"ticker": "LEN", "name": "Lennar"},
    LFC: {"ticker": "LFC", "name": "China Life Insurance"},
    LH: {"ticker": "LH", "name": "LabCorp"},
    LHX: {"ticker": "LHX", "name": "L3Harris"},
    LI: {"ticker": "LI", "name": "Li Auto"},
    LIN: {"ticker": "LIN", "name": "Linde"},
    LLY: {"ticker": "LLY", "name": "Eli Lilly"},
    LMT: {"ticker": "LMT", "name": "Lockheed Martin"},
    LNG: {"ticker": "LNG", "name": "Cheniere Energy"},
    LOB: {"ticker": "LOB", "name": "Live Oak Bansch"},
    LOGI: {"ticker": "LOGI", "name": "Logitech"},
    LOW: {"ticker": "LOW", "name": "Lowe's"},
    LPCN: {"ticker": "LPCN", "name": "Lipocine"},
    LSXMA: {"ticker": "LSXMA", "name": "Liberty Media"},
    LSXMB: {"ticker": "LSXMB", "name": "Liberty Media"},
    LU: {"ticker": "LU", "name": "Lufax"},
    LULU: {"ticker": "LULU", "name": "Lululemon Athletica"},
    LUV: {"ticker": "LUV", "name": "Southwest Airlines"},
    LVS: {"ticker": "LVS", "name": "Las Vegas Sands"},
    LYB: {"ticker": "LYB", "name": "LyondelBassel"},
    LYFT: {"ticker": "LYFT", "name": "Lyft"},
    LYG: {"ticker": "LYG", "name": "Lloyds Banking"},
    LYV: {"ticker": "LYV", "name": "Live Nation Entertainment"},
    M: {"ticker": "M", "name": "Macy's"},
    MA: {"ticker": "MA", "name": "Mastercard"},
    MAA: {"ticker": "MAA", "name": "Mid-America Apartment Communities"},
    MAR: {"ticker": "MAR", "name": "Mariott"},
    MCD: {"ticker": "MCD", "name": "McDonald's"},
    MCHP: {"ticker": "MCHP", "name": "Microchip Technology"},
    MCK: {"ticker": "MCK", "name": "McKesson"},
    MCO: {"ticker": "MCO", "name": "Moody's"},
    MDB: {"ticker": "MDB", "name": "MongoDB"},
    MDLZ: {"ticker": "MDLZ", "name": "Mondelez International"},
    MDT: {"ticker": "MDT", "name": "Medtronic"},
    MELI: {"ticker": "MELI", "name": "MercadoLibre"},
    MET: {"ticker": "MET", "name": "MetLife"},
    MFC: {"ticker": "MFC", "name": "Manulife"},
    MFG: {"ticker": "MFG", "name": "Mizuho"},
    MGA: {"ticker": "MGA", "name": "Magna"},
    MGM: {"ticker": "MGM", "name": "MGM Resorts"},
    MHK: {"ticker": "MHK", "name": "Mohawk Industries"},
    MKC: {"ticker": "MKC", "name": "McCormick & Company"},
    MKL: {"ticker": "MKL", "name": "Markel"},
    MKTX: {"ticker": "MKTX", "name": "MarketAxess"},
    MLM: {"ticker": "MLM", "name": "Martin Marietta Materials"},
    MMC: {"ticker": "MMC", "name": "Marsh & McLennan"},
    MMM: {"ticker": "MMM", "name": "3M"},
    MNST: {"ticker": "MNST", "name": "Monster"},
    MO: {"ticker": "MO", "name": "Altria"},
    MOH: {"ticker": "MOH", "name": "Molina Healthcare"},
    MPC: {"ticker": "MPC", "name": "Marathon Petroleum"},
    MPLX: {"ticker": "MPLX", "name": "MPLX LP"},
    MPWR: {"ticker": "MPWR", "name": "Monolithic Power Systems"},
    MRK: {"ticker": "MRK", "name": "Merck"},
    MRNA: {"ticker": "MRNA", "name": "Moderna"},
    MRO: {"ticker": "MRO", "name": "Marathon Oil"},
    MRVL: {"ticker": "MRVL", "name": "Marvell Tecnhology"},
    MS: {"ticker": "MS", "name": "Morgan Stanley"},
    MSCI: {"ticker": "MSCI", "name": "MSCI"},
    MSFT: {"ticker": "MSFT", "name": "Microsoft"},
    MSI: {"ticker": "MSI", "name": "Motorola Solutions"},
    MT: {"ticker": "MT", "name": "Arcelor Mittal"},
    MTB: {"ticker": "MTB", "name": "M&T Bank"},
    MTCH: {"ticker": "MTCH", "name": "Match"},
    MTD: {"ticker": "MTD", "name": "Mettler-Toledo"},
    MU: {"ticker": "MU", "name": "Micron"},
    MUFG: {"ticker": "MUFG", "name": "Mitsubishi"},
    MVIS: {"ticker": "MVIS", "name": "MicroVision"},
    MXIM: {"ticker": "MXIM", "name": "Maxim Integrated"},
    NAKD: {"ticker": "NAKD", "name": "Naked Brand"},
    NCLH: {"ticker": "NCLH", "name": "Norwegian Cruise Line"},
    NDAQ: {"ticker": "NDAQ", "name": "Nasdaq"},
    NEE: {"ticker": "NEE", "name": "NextEra Energy"},
    NET: {"ticker": "NET", "name": "Cloudflare"},
    NFLX: {"ticker": "NFLX", "name": "Netflix"},
    NGG: {"ticker": "NGG", "name": "National Grid Transco"},
    NIO: {"ticker": "NIO", "name": "Nio"},
    NKE: {"ticker": "NKE", "name": "Nike"},
    NKLA: {"ticker": "NKLA", "name": "Nikola"},
    NLOK: {"ticker": "NLOK", "name": "NortonLifeLock"},
    NMR: {"ticker": "NMR", "name": "Nomura Holdings"},
    NNDM: {"ticker": "NNDM", "name": "Nano Dimension"},
    NOC: {"ticker": "NOC", "name": "Northrop Grumman"},
    NOK: {"ticker": "NOK", "name": "Nokia"},
    NOVA: {"ticker": "NOVA", "name": "Sunnova Energy"},
    NOW: {"ticker": "NOW", "name": "ServiceNow"},
    NRZ: {"ticker": "NRZ", "name": "New Residential Invesment"},
    NSC: {"ticker": "NSC", "name": "Norfolk Southern Corporation"},
    NTAP: {"ticker": "NTAP", "name": "NetApp"},
    NTES: {"ticker": "NTES", "name": "NetEase"},
    NTR: {"ticker": "NTR", "name": "Nutrien"},
    NTRS: {"ticker": "NTRS", "name": "Northern Trust"},
    NUE: {"ticker": "NUE", "name": "Nucor"},
    NVCR: {"ticker": "NVCR", "name": "NovoCure"},
    NVDA: {"ticker": "NVDA", "name": "NVIDIA"},
    NVO: {"ticker": "NVO", "name": "Novo Nordisk"},
    NVR: {"ticker": "NVR", "name": "NVR"},
    NVS: {"ticker": "NVS", "name": "Novartis AG"},
    NWG: {"ticker": "NWG", "name": "NatWest"},
    NWSA: {"ticker": "NWSA", "name": "News Corp"},
    NXPI: {"ticker": "NXPI", "name": "NXP Semiconductors"},
    O: {"ticker": "O", "name": "Realty Income"},
    OCGN: {"ticker": "OCGN", "name": "Ocugen"},
    ODFL: {"ticker": "ODFL", "name": "Old Dominion Freight Line"},
    OGI: {"ticker": "OGI", "name": "OrganiGram"},
    OKE: {"ticker": "OKE", "name": "ONEOK"},
    OKTA: {"ticker": "OKTA", "name": "Okta"},
    OMC: {"ticker": "OMC", "name": "Omnicom"},
    ON: {"ticker": "ON", "name": "ON Semiconductor"},
    ORAN: {"ticker": "ORAN", "name": "Orange"},
    ORCL: {"ticker": "ORCL", "name": "Oracle"},
    ORLY: {"ticker": "ORLY", "name": "O'Reilly"},
    OTIS: {"ticker": "OTIS", "name": "Otis"},
    OTLK: {"ticker": "OTLK", "name": "Outlook Therapeutics"},
    OVID: {"ticker": "OVID", "name": "Ovid Therapeutics"},
    OXY: {"ticker": "OXY", "name": "Occidental Petroleum"},
    PAAS: {"ticker": "PAAS", "name": "Pan American Silver"},
    PAGS: {"ticker": "PAGS", "name": "PagSeguro Digital"},
    PANW: {"ticker": "PANW", "name": "Palo Alto Networks"},
    PATH: {"ticker": "PATH", "name": "UiPath"},
    PAYC: {"ticker": "PAYC", "name": "Paycom Software"},
    PAYX: {"ticker": "PAYX", "name": "Paychex"},
    PBA: {"ticker": "PBA", "name": "Pembina Pipeline"},
    PBR: {"ticker": "PBR", "name": "Petroleo Brasileiro"},
    PCAR: {"ticker": "PCAR", "name": "PACCAR"},
    PCG: {"ticker": "PCG", "name": "Pacific Gas & Electric"},
    PEAK: {"ticker": "PEAK", "name": "Healthpeak Properties"},
    PEG: {"ticker": "PEG", "name": "Public Service Enterprise"},
    PENN: {"ticker": "PENN", "name": "Penn National Gambling"},
    PEP: {"ticker": "PEP", "name": "Pepsi"},
    PFE: {"ticker": "PFE", "name": "Pfizer"},
    PFG: {"ticker": "PFG", "name": "principal Financial Group"},
    PG: {"ticker": "PG", "name": "Procter & Gamble"},
    PGR: {"ticker": "PGR", "name": "Progressive"},
    PH: {"ticker": "PH", "name": "Parker-Hannifin"},
    PHG: {"ticker": "PHG", "name": "Royal Philips"},
    PINS: {"ticker": "PINS", "name": "Pinterest"},
    PKI: {"ticker": "PKI", "name": "PerkinElmer"},
    PKX: {"ticker": "PKX", "name": "POSCO"},
    PLAY: {"ticker": "PLAY", "name": "Dave & Buster's"},
    PLD: {"ticker": "PLD", "name": "Prologis"},
    PLTR: {"ticker": "PLTR", "name": "Palantir Technologies"},
    PLUG: {"ticker": "PLUG", "name": "Plug Power"},
    PM: {"ticker": "PM", "name": "Philip Morris"},
    PNC: {"ticker": "PNC", "name": "PNC Financial Services Group"},
    PODD: {"ticker": "PODD", "name": "Insulet"},
    POOL: {"ticker": "POOL", "name": "Pool Corp"},
    POSH: {"ticker": "POSH", "name": "Poshmark"},
    PPD: {"ticker": "PPD", "name": "PPD"},
    PPG: {"ticker": "PPG", "name": "PPG"},
    PPL: {"ticker": "PPL", "name": "PPL"},
    PRU: {"ticker": "PRU", "name": "Prudential Financial"},
    PSA: {"ticker": "PSA", "name": "Public Storage"},
    PSEC: {"ticker": "PSEC", "name": "Prospect Capital"},
    PSX: {"ticker": "PSX", "name": "Phillips 66"},
    PTC: {"ticker": "PTC", "name": "PTC"},
    PTON: {"ticker": "PTON", "name": "Peloton"},
    PTR: {"ticker": "PTR", "name": "PetroChina"},
    PUK: {"ticker": "PUK", "name": "Prudential Public"},
    PXD: {"ticker": "PXD", "name": "Pioneer"},
    PYPL: {"ticker": "PYPL", "name": "PayPal"},
    QCOM: {"ticker": "QCOM", "name": "QUALCOMM"},
    QRVO: {"ticker": "QRVO", "name": "Qorvo"},
    QSR: {"ticker": "QSR", "name": "Restaurant Brands"},
    RACE: {"ticker": "RACE", "name": "Ferrari"},
    RBLX: {"ticker": "RBLX", "name": "Roblox"},
    RCI: {"ticker": "RCI", "name": "Rogers Communication"},
    RCL: {"ticker": "RCL", "name": "Royal Caribbean Group"},
    RDFN: {"ticker": "RDFN", "name": "Redfin"},
    Real: {"ticker": "Real", "name": "The RealReal"},
    REGN: {"ticker": "REGN", "name": "Regeneron Pharmaceuticals"},
    RELX: {"ticker": "RELX", "name": "RELX"},
    RF: {"ticker": "RF", "name": "Regions Financial"},
    RIO: {"ticker": "RIO", "name": "Rio Tinto"},
    RIOT: {"ticker": "RIOT", "name": "Riot Blockchain"},
    RJF: {"ticker": "RJF", "name": "Raymond James Financial"},
    RLX: {"ticker": "RLX", "name": "RLX Technology"},
    RMD: {"ticker": "RMD", "name": "ResMed"},
    RNG: {"ticker": "RNG", "name": "RingCentral"},
    ROK: {"ticker": "ROK", "name": "Rockwell Automation"},
    ROKU: {"ticker": "ROKU", "name": "Roku"},
    ROL: {"ticker": "ROL", "name": "Rollins"},
    ROP: {"ticker": "ROP", "name": "Roper"},
    ROST: {"ticker": "ROST", "name": "Ross"},
    RPRX: {"ticker": "RPRX", "name": "Royalty Pharma"},
    RSG: {"ticker": "RSG", "name": "Reupublic Services"},
    RTX: {"ticker": "RTX", "name": "Raytheon Technologies"},
    RY: {"ticker": "RY", "name": "Royal Bank of Canada"},
    RYAA: {"ticker": "RYAAY", "name": "Ryanair Holdings"},
    RYCE: {"ticker": "RYCEY", "name": "Rolls-Royce"},
    SAN: {"ticker": "SAN", "name": "Banco Santander"},
    SAP: {"ticker": "SAP", "name": "SAP SE"},
    SAVE: {"ticker": "SAVE", "name": "Spirit Airlines"},
    SBAC: {"ticker": "SBAC", "name": "SBA Communications"},
    SBUX: {"ticker": "SBUX", "name": "Starbucks"},
    SCCO: {"ticker": "SCCO", "name": "Southern Copper"},
    SCHW: {"ticker": "SCHW", "name": "Charles Schwab"},
    SE: {"ticker": "SE", "name": "Sea Limited AMerican Depositary Shares"},
    SENS: {"ticker": "SENS", "name": "Senseonics"},
    SGEN: {"ticker": "SGEN", "name": "Seagen"},
    SHG: {"ticker": "SHG", "name": "Shinhan Financial Group"},
    SHOP: {"ticker": "SHOP", "name": "Shopify"},
    SHW: {"ticker": "SHW", "name": "Sherwin-Williams"},
    SIRI: {"ticker": "SIRI", "name": "Sirius XM"},
    SIVB: {"ticker": "SIVB", "name": "SVB"},
    SKM: {"ticker": "SKM", "name": "SK Telecom"},
    SLB: {"ticker": "SLB", "name": "Schlumberger"},
    SLF: {"ticker": "SLF", "name": "Sun Life"},
    SLV: {"ticker": "SLV", "name": "iShares Silver trust"},
    SMFG: {"ticker": "SMFG", "name": "Sumitomo Mitsui"},
    SNA: {"ticker": "SNA", "name": "Snap-On"},
    SNAP: {"ticker": "SNAP", "name": "Snap"},
    SNDL: {"ticker": "SNDL", "name": "Sundial Growers"},
    SNN: {"ticker": "SNN", "name": "Smith & Nephew"},
    SNOW: {"ticker": "SNOW", "name": "Snowflake"},
    SNP: {"ticker": "SNP", "name": "China Petroleum & Chemical Corporation"},
    SNPS: {"ticker": "SNPS", "name": "Synopsys"},
    SNY: {"ticker": "SNY", "name": "Sanofi"},
    SO: {"ticker": "SO", "name": "Southern Company"},
    SONY: {"ticker": "SONY", "name": "Sony"},
    SOS: {"ticker": "SOS", "name": "SOS Limited"},
    SPCE: {"ticker": "SPCE", "name": "Virgin Galactic Holdings"},
    SPG: {"ticker": "SPG", "name": "Simon Property Group"},
    SPGI: {"ticker": "SPGI", "name": "S&P Global"},
    SPLK: {"ticker": "SPLK", "name": "Splunk"},
    SPOT: {"ticker": "SPOT", "name": "Spotify"},
    SPPI: {"ticker": "SPPI", "name": "Spectrum Pharmaceuticals"},
    SPY: {"ticker": "SPY", "name": "SPDR S&P 500 ETF"},
    SQ: {"ticker": "SQ", "name": "Square"},
    SRE: {"ticker": "SRE", "name": "Sempra Energy"},
    SSNC: {"ticker": "SSNC", "name": "SS&C Technologies"},
    STE: {"ticker": "STE", "name": "STERIS"},
    STLA: {"ticker": "STLA", "name": "Stellantis"},
    STM: {"ticker": "STM", "name": "STMicroelectronics"},
    STNE: {"ticker": "STNE", "name": "StoneCo"},
    STT: {"ticker": "STT", "name": "State Street"},
    STX: {"ticker": "STX", "name": "Seagate Technology"},
    STZ: {"ticker": "STZ", "name": "Constellation Brands"},
    SU: {"ticker": "SU", "name": "Suncor Energy"},
    SUI: {"ticker": "SUI", "name": "Sun Communities"},
    SUZ: {"ticker": "SUZ", "name": "Suzano"},
    SVM: {"ticker": "SVM", "name": "Silvercorp Metals"},
    SWK: {"ticker": "SWK", "name": "Stanley Black & Decker"},
    SWKS: {"ticker": "SWKS", "name": "Skyworks"},
    SYF: {"ticker": "SYF", "name": "Synchrony"},
    SYK: {"ticker": "SYK", "name": "Stryker"},
    SYY: {"ticker": "SYY", "name": "Sysco"},
    T: {"ticker": "T", "name": "AT&T"},
    TAK: {"ticker": "TAK", "name": "Takeda Pharmaceutical"},
    TAL: {"ticker": "TAL", "name": "TAL Education"},
    TCOM: {"ticker": "TCOM", "name": "Trip.com"},
    TD: {"ticker": "TD", "name": "Toronto Dominion Bank"},
    TDG: {"ticker": "TDG", "name": "Transdigm"},
    TDOC: {"ticker": "TDOC", "name": "Teladoc Health"},
    TDY: {"ticker": "TDY", "name": "Teledyne"},
    TEAM: {"ticker": "TEAM", "name": "Atlassian"},
    TECH: {"ticker": "TECH", "name": "Bio-Techne"},
    TEF: {"ticker": "TEF", "name": "Telefonica"},
    TEL: {"ticker": "TEL", "name": "TE Connectivity"},
    TER: {"ticker": "TER", "name": "Teradyne"},
    TFC: {"ticker": "TFC", "name": "Truist Financial"},
    TFX: {"ticker": "TFX", "name": "Teleflex"},
    TGT: {"ticker": "TGT", "name": "Target"},
    TJX: {"ticker": "TJX", "name": "TJX Companies"},
    TLK: {"ticker": "TLK", "name": "PT Telekommunikasi Indonesia"},
    TLRY: {"ticker": "TLRY", "name": "Tilray"},
    TM: {"ticker": "TM", "name": "Toyota"},
    TME: {"ticker": "TME", "name": "Tencent Music Entertainment"},
    TMO: {"ticker": "TMO", "name": "Thermo Fisher Scientific"},
    TMUS: {"ticker": "TMUS", "name": "T-Mobile"},
    TNXP: {"ticker": "TNXP", "name": "Tonix Pharmaceuticals"},
    TOT: {"ticker": "TOT", "name": "Total"},
    TRCH: {"ticker": "TRCH", "name": "Torchlight Energy Resources"},
    TRI: {"ticker": "TRI", "name": "Thomson Reuters"},
    TRMB: {"ticker": "TRMB", "name": "Trimble"},
    TROW: {"ticker": "TROW", "name": "T.Rowe Price"},
    TRP: {"ticker": "TRP", "name": "TC Energy"},
    TRU: {"ticker": "TRU", "name": "TransUnion"},
    TRV: {"ticker": "TRV", "name": "Travelers"},
    TSCO: {"ticker": "TSCO", "name": "Tractor Supply"},
    TSLA: {"ticker": "TSLA", "name": "Tesla"},
    TSM: {"ticker": "TSM", "name": "Taiwan Semiconductor Manufacturing"},
    TSN: {"ticker": "TSN", "name": "Tyson Foods"},
    TTD: {"ticker": "TTD", "name": "The Trade Desk"},
    TTWO: {"ticker": "TTWO", "name": "Take-Two Interactive Software"},
    TU: {"ticker": "TU", "name": "Telus"},
    TW: {"ticker": "TW", "name": "Tradeweb Markets"},
    TWLO: {"ticker": "TWLO", "name": "Twilio"},
    TWTR: {"ticker": "TWTR", "name": "Twitter"},
    TXG: {"ticker": "TXG", "name": "10x Genomics"},
    TXMD: {"ticker": "TXMD", "name": "TherapeuticsMD"},
    TXN: {"ticker": "TXN", "name": "Texas Instruments"},
    TXT: {"ticker": "TXT", "name": "Textron"},
    TYL: {"ticker": "TYL", "name": "Tyler Technologies"},
    U: {"ticker": "U", "name": "Unity Software"},
    UA: {"ticker": "UA", "name": "Under Armour"},
    UAL: {"ticker": "UAL", "name": "United Airlines"},
    UBER: {"ticker": "UBER", "name": "Uber"},
    UBS: {"ticker": "UBS", "name": "UBS Group"},
    UI: {"ticker": "UI", "name": "Ubiquiti"},
    UL: {"ticker": "UL", "name": "Unilever PLC"},
    ULTA: {"ticker": "ULTA", "name": "Ulta Beauty"},
    UMC: {"ticker": "UMC", "name": "United Microelectronics"},
    UNH: {"ticker": "UNH", "name": "UnitedHealth"},
    UNP: {"ticker": "UNP", "name": "Union Pacific"},
    UPS: {"ticker": "UPS", "name": "United Parcel Service"},
    UPWK: {"ticker": "UPWK", "name": "Upwork"},
    URI: {"ticker": "URI", "name": "United Rentals"},
    USB: {"ticker": "USB", "name": "US Bank"},
    V: {"ticker": "V", "name": "Visa"},
    VALE: {"ticker": "VALE", "name": "Vale"},
    VEEV: {"ticker": "VEEV", "name": "Veeva Systems"},
    VFC: {"ticker": "VFC", "name": "V.F. Corporation"},
    VIAC: {"ticker": "VIAC", "name": "ViacomCBS Class B"},
    VIAC: {"ticker": "VIACA", "name": "ViacomCBS Class A"},
    VICI: {"ticker": "VICI", "name": "VICI Properties"},
    VIPS: {"ticker": "VIPS", "name": "Vipshop Holdings"},
    VLO: {"ticker": "VLO", "name": "Valero Energy"},
    VMC: {"ticker": "VMC", "name": "Vulcan Materials"},
    VMW: {"ticker": "VMW", "name": "Vmware"},
    VOD: {"ticker": "VOD", "name": "Vodafone"},
    VOO: {"ticker": "VOO", "name": "Vanguard S&P 500 ETF"},
    VRSK: {"ticker": "VRSK", "name": "Verisk Analytics"},
    VRSN: {"ticker": "VRSN", "name": "VeriSign"},
    VRTX: {"ticker": "VRTX", "name": "Vertex Pharmaceuticals"},
    VTI: {"ticker": "VTI", "name": "Vanguard Total Stock Market ETF"},
    VTR: {"ticker": "VTR", "name": "Ventas"},
    VTRS: {"ticker": "VTRS", "name": "Viatris"},
    VXRT: {"ticker": "VXRT", "name": "Vaxart"},
    VZ: {"ticker": "VZ", "name": "Verizon"},
    W: {"ticker": "W", "name": "Wayfair"},
    WAB: {"ticker": "WAB", "name": "Westinghouse Air Brake Technologies"},
    WAT: {"ticker": "WAT", "name": "Waters"},
    WBA: {"ticker": "WBA", "name": "Walgreens"},
    WBK: {"ticker": "WBK", "name": "Westpac Banking"},
    WCN: {"ticker": "WCN", "name": "Waste Connections"},
    WDAY: {"ticker": "WDAY", "name": "Workday"},
    WDC: {"ticker": "WDC", "name": "Western Digital"},
    WEC: {"ticker": "WEC", "name": "WEC Energy"},
    WELL: {"ticker": "WELL", "name": "Welltower"},
    WFC: {"ticker": "WFC", "name": "Wells Fargo"},
    WHR: {"ticker": "WHR", "name": "Whirlpool"},
    WISH: {"ticker": "WISH", "name": "ContextLogic"},
    WIT: {"ticker": "WIT", "name": "Wipro"},
    WIX: {"ticker": "WIX", "name": "Wix.com"},
    WKHS: {"ticker": "WKHS", "name": "Workhorse"},
    WLTW: {"ticker": "WLTW", "name": "Willis Towers Watson"},
    WM: {"ticker": "WM", "name": "Waste Management"},
    WMB: {"ticker": "WMB", "name": "Williams Companies"},
    WMG: {"ticker": "WMG", "name": "Warner Music Group"},
    WMT: {"ticker": "WMT", "name": "Walmart"},
    WOOF: {"ticker": "WOOF", "name": "Petco Health and Wellness"},
    WORK: {"ticker": "WORK", "name": "Slack"},
    WPM: {"ticker": "WPM", "name": "Wheaton Precious Metals Corp"},
    WPP: {"ticker": "WPP", "name": "WPP"},
    WRK: {"ticker": "WRK", "name": "Westrock"},
    WST: {"ticker": "WST", "name": "West Pharmaceutical"},
    WY: {"ticker": "WY", "name": "Weyerhaeuser"},
    WYNN: {"ticker": "WYNN", "name": "Wynn Resorts"},
    XEL: {"ticker": "XEL", "name": "Xcel Energy"},
    XLNX: {"ticker": "XLNX", "name": "Xilinx"},
    XM: {"ticker": "XM", "name": "Qualtrics International"},
    XOM: {"ticker": "XOM", "name": "Exxon Mobil"},
    XP: {"ticker": "XP", "name": "XP Inc"},
    XPEV: {"ticker": "XPEV", "name": "Xpeng"},
    XPO: {"ticker": "XPO", "name": "XPO Logistics"},
    XYL: {"ticker": "XYL", "name": "Xylem"},
    YNDX: {"ticker": "YNDX", "name": "Yandex"},
    YUM: {"ticker": "YUM", "name": "Yum!"},
    YUMC: {"ticker": "YUMC", "name": "Yum China"},
    Z: {"ticker": "Z", "name": "Zillow Class C"},
    ZBH: {"ticker": "ZBH", "name": "Zimmer Biomet"},
    ZBRA: {"ticker": "ZBRA", "name": "Zebra Technologies"},
    ZEN: {"ticker": "ZEN", "name": "Zendesk"},
    ZG: {"ticker": "ZG", "name": "Zillow Class A"},
    ZI: {"ticker": "ZI", "name": "ZoomInfo"},
    ZM: {"ticker": "ZM", "name": "Zoom"},
    ZNGA: {"ticker": "ZNGA", "name": "Zynga"},
    ZOM: {"ticker": "ZOM", "name": "Zomedica"},
    ZS: {"ticker": "ZS", "name": "Zscaler"},
    ZTO: {"ticker": "ZTO", "name": "ZTO Express"},
    ZTS: {"ticker": "ZTS", "name": "Zoetis"}
};
export default searchList;




